### ISSUE TITLE
Incompatibility with TerraBlender

### ISSUE THREAD

**Issue by sharkck** [McJty/RFToolsDimensions#432]
Issue description: 
Reopening https://github.com/McJtyMods/RFToolsDimensions/issues/424
Per TerraBlender, the issues in question appear to be in RFTools itself.

Steps to reproduce: 
Create a world

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.4
* McJtyLib: 7.1.5
* RFTools: 4.1.4
* RFTools Dimensions: 9.1.1

Possibly incompatible mods: 

TerraBlender

Relevant logs, if any: 

N/A

**Comment by sharkck** [comment]
I opened an issue with TerraBlender and they looked at it and are determining the following from: https://github.com/Glitchfiend/TerraBlender/issues/111

[Adubbz](https://github.com/Adubbz) commented [Feb 15, 2023](https://github.com/Glitchfiend/TerraBlender/issues/111#issuecomment-1430823166) •

As mentioned on Discord, this would likely be because modded biomes aren’t being added to their possible biomes list in their biome source. TerraBlender is able to do this itself with Vanilla’s biome source, but not theirs given they are created at runtime. Accordingly, this will need to be handled on their side.

[Adubbz](https://github.com/Adubbz) commented [Feb 15, 2023](https://github.com/Glitchfiend/TerraBlender/issues/111#issuecomment-1430826853)

With the above in mind, I’m going to close this, since I don’t believe it can be resolved on TerraBlender’s side.

**Comment by McJty** [comment]
I'll check this out

**Comment by McJty** [comment]
I think I have a fix. Will test further and release soon

**Comment by sharkck** [comment]
Any updates on this?

**Comment by McJty** [comment]
This was fixed some time ago. Sorry. Forgot to close

**Comment by sharkck** [comment]
This is still not fixed.  Updated to rftoolsdim-1.19.2-9.1.2.jar and still the worlds do not generate properly.  Even doing a simple world with normal terrain dimlet just generates a water world with no platform over and over again or a world of nothing but stone blocks and you start 80m below the surface with no platform.

**Comment by sharkck** [comment]
![image](https://user-images.githubusercontent.com/960552/229327570-76dff028-f93a-447c-a9db-ea98c8dd1362.png)

**Comment by sharkck** [comment]
![image](https://user-images.githubusercontent.com/960552/229327574-6860ee78-2283-41a6-a963-ceda26dbdc71.png)

**Comment by sharkck** [comment]
Updated all RFTools mods to latest as well as latest forge for 1.19.2.

RFToolsDIM ver: rftoolsdim-1.19.2-9.1.3.jar

**Comment by McJty** [comment]
Hold on, I'm a little confused. You see normal terrain but I see a void world? Can you use matching screenshots with the type of world you actually created? Because for me a 'normal' terrain actually generates a normal terrain world and not void

**Comment by McJty** [comment]
What version of TerraBlender are you using?

**Comment by McJty** [comment]
@sharkck ?

**Comment by daniele-bondi** [comment]
I'm having problems with dimensions too on 1.18. I'm assuming it's because of this bug.

Versions:
* Minecraft: 1.18.2
* Forge: 40.2.13
* McJtyLib: 1.18-**6.0.20**
* RFToolsBase: 1.18-**3.0.12**
* RFTools Dimensions: 1.18-**8.0.10**
* TerraBlender: 1.2.0.126


Probably related:
- https://github.com/Glitchfiend/TerraBlender/issues/75
- https://github.com/Glitchfiend/TerraBlender/issues/111

**Comment by ryleestatler** [comment]
I'm also having these issues in 1.18.2, I have every mod up to date as of making this comment

Edit: I just removed terrablender, it also causes issues in other mods and its just not worth it imo. I used biomes o plenty for more blocks and biomes that rftools could pull from, and now I just use mods that add a lot of blocks like thermal expansion and mekanism
